name: "mi primer workflow"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    
jobs:
  compile:
   runs-on: ubuntu-latest 
   steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          
      - name: Install
        working-directory: "appSQL_v3/"
        run: |
          npm ci --silent
          npm run build
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: appSQL_v3/build
    


